import type { EcosystemPageContent } from "@/components/marketing/EcosystemPage";

export const ecosystemPages = {
  acheter: {
    path: "/acheter",
    eyebrow: "Acheter sur Sugu",
    title: "Trouvez vos produits et commandez avec un parcours local clair.",
    description: "Sugu rassemble produits, boutiques, livraison et paiement pour rendre l’achat en ligne plus simple au Burkina Faso.",
    intro: "Cette page guide les acheteurs vers les catégories, les boutiques et l’assistance sans mélanger les espaces réservés aux professionnels.",
    features: [
      { title: "Produits à découvrir", description: "Parcourez les catégories et comparez les offres disponibles sur la marketplace." },
      { title: "Boutiques identifiables", description: "Consultez les vitrines des vendeurs et les informations rattachées à leurs offres." },
      { title: "Commande suivie", description: "Retrouvez les étapes utiles depuis votre compte et les outils de suivi prévus." },
      { title: "Paiement relié", description: "SuguPay accompagne le règlement des commandes éligibles dans l’écosystème Sugu." },
    ],
    cta: { label: "Découvrir les produits", href: "/search" },
    secondaryCta: { label: "Voir les boutiques", href: "/stores" },
  },
  vendeurs: {
    path: "/vendeurs",
    eyebrow: "Vendre sur Sugu",
    title: "Développez votre boutique avec l’espace professionnel Sugu Pro.",
    description: "Présentez vos produits sur la marketplace et pilotez catalogue, commandes, livraison et revenus depuis Sugu Pro.",
    intro: "La marketplace reste l’espace public d’achat. Sugu Pro fournit aux vendeurs les outils nécessaires pour administrer leur activité.",
    features: [
      { title: "Catalogue", description: "Préparez des fiches produits claires avec prix, médias et disponibilité." },
      { title: "Commandes", description: "Traitez chaque vente à partir d’un statut partagé avec les autres intervenants." },
      { title: "Livraison", description: "Coordonnez la préparation et la prise en charge du colis." },
      { title: "Suivi d’activité", description: "Retrouvez les informations opérationnelles et financières utiles à votre boutique." },
    ],
    cta: { label: "Découvrir l’espace vendeur", href: "https://pro.sugu.pro/vendeurs", external: true },
    secondaryCta: { label: "Voir les fournisseurs", href: "/fournisseurs" },
  },
  "agences-de-livraison": {
    path: "/agences-de-livraison",
    eyebrow: "Agences de livraison",
    title: "Reliez votre équipe de livraison aux commandes Sugu.",
    description: "Les agences partenaires utilisent Sugu Pro pour organiser les missions, affecter les coursiers et suivre les livraisons.",
    intro: "Une agence n’a pas besoin de parcourir la marketplace pour gérer ses opérations : son espace dédié se trouve sur Sugu Pro.",
    features: [
      { title: "Missions centralisées", description: "Recevez et consultez les livraisons confiées à votre organisation." },
      { title: "Affectation", description: "Associez chaque mission au coursier chargé de son exécution." },
      { title: "Statuts partagés", description: "Suivez l’avancement avec une information commune aux équipes concernées." },
      { title: "Historique", description: "Conservez une trace structurée des opérations réalisées." },
    ],
    cta: { label: "Découvrir l’espace agence", href: "https://pro.sugu.pro/agences-de-livraison", external: true },
    secondaryCta: { label: "Comprendre Sugu Pro", href: "https://pro.sugu.pro/fonctionnalites", external: true },
  },
  coursiers: {
    path: "/coursiers",
    eyebrow: "Coursiers partenaires",
    title: "Un parcours mobile pour exécuter chaque livraison avec clarté.",
    description: "Les coursiers consultent leurs missions, mettent à jour les statuts et suivent leur activité depuis leur espace Sugu Pro.",
    intro: "Le rôle du coursier intervient après la commande. Son interface privilégie les informations nécessaires sur le terrain.",
    features: [
      { title: "Mission", description: "Consultez la livraison affectée et les informations nécessaires à la prise en charge." },
      { title: "Progression", description: "Mettez à jour les étapes utiles pendant l’exécution de la mission." },
      { title: "Validation", description: "Finalisez la remise selon les mécanismes prévus par la commande." },
      { title: "Activité", description: "Retrouvez l’historique et les revenus associés à vos livraisons." },
    ],
    cta: { label: "Découvrir l’espace coursier", href: "https://pro.sugu.pro/coursiers", external: true },
    secondaryCta: { label: "Créer mon accès", href: "https://pro.sugu.pro/signup/driver", external: true },
  },
  sugupay: {
    path: "/sugupay",
    eyebrow: "Paiement SuguPay",
    title: "Le paiement officiel relié aux commandes Sugu.",
    description: "SuguPay accompagne le paiement Mobile Money des commandes éligibles dans une expérience simple et sécurisée.",
    intro: "SuguPay possède son propre site public sur sugupay.net tandis que le paiement effectif reste rattaché à la commande concernée.",
    features: [
      { title: "Commande reconnue", description: "Le paiement est présenté dans le contexte de la commande à régler." },
      { title: "Mobile Money", description: "Les réseaux disponibles sont proposés selon le pays et le numéro saisi." },
      { title: "Statut relié", description: "La confirmation du paiement alimente le suivi de la commande." },
      { title: "Assistance", description: "Des points d’aide orientent l’acheteur lorsqu’il a besoin d’accompagnement." },
    ],
    cta: { label: "Découvrir SuguPay", href: "https://sugupay.net/", external: true },
    secondaryCta: { label: "Voir le fonctionnement", href: "https://sugupay.net/fonctionnement", external: true },
  },
} satisfies Record<string, EcosystemPageContent>;
